name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment
        run: |
          curl -X POST http://nobrakes.cz/deploy \
               -H "x-deploy-token: hardcoded-supersecret-nbrtoken"