name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment
        run: |
          echo "Triggering deploy..."
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST https://nobrakes.cz/deploy)
          echo "HTTP status: $RESPONSE"
          echo "Response body:"
          cat response.txt

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Deploy failed!"
            exit 1
          fi

          echo "Deploy succeeded!"

