name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment
        run: |
          echo "Triggering deploy..."
          mkdir -p tmp
          RESPONSE=$(curl -s -S -o logs/curl-response.txt -w "%{http_code}" -X POST -L https://nobrakes.cz/deploy || echo "000")
          echo "HTTP status: $RESPONSE"
          echo "Response body:"
          cat logs/curl-response.txt || echo "(no response)"
          
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Deploy failed!"
            exit 1
          fi

          echo "Deploy succeeded!"

